### ISSUE TITLE
feat: Hover could contain more infomation

### ISSUE THREAD

**Issue by cutecutecat** [tilt-dev/starlark-lsp#45]
Hello, I am a developer from [tensorchord](https://github.com/tensorchord). We use starlark-lsp as a denepndency to build our [LSP Server](https://github.com/tensorchord/envd-lsp). 
Much thanks for this project and its contributors!

I have a feature recommendation for starlark-lsp. If you think it is acceptable, I would be happy to help on it. If it could be merged, I could upgrade our project to introduce it either.

When we use `Python` extension, it would display `Parameters` and `Returns` for functions.
![image](https://user-images.githubusercontent.com/19801166/215239420-a2872afb-760a-4801-a012-2ec0f25e1658.png)

Hovever, `starlark-lsp` could only show first line(document) for `Hover`, it would be better for user if `Hover` could output arguments types.

Related issue: https://github.com/tensorchord/envd-lsp/issues/35

**Comment by nicksieger** [comment]
Hi, thanks for submitting an issue! We'd be happy to accept improvements to Hover, please submit a pull request and we can continue the discussion there.
